services:
  api:
    build:
      context: ..
      dockerfile: scripts/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=chatapp;Username=postgres;Password=altaseb;Include Error Detail=true
      - JwtSettings__Secret=bbd8dab53ffc6dd9ef781cc176a2aaef3ce2e15a292584f3112fac2010bfccee
      - JwtSettings__Issuer=ChatApplication
      - JwtSettings__Audience=ChatApplication
      - JwtSettings__ExpiryMinutes=60
      - RedisSettings__ConnectionString=redis:6379
      - RabbitMqSettings__Host=rabbitmq
      - RabbitMqSettings__Port=5672
      - RabbitMqSettings__Username=guest
      - RabbitMqSettings__Password=guest
      - Cloudinary__CloudName=dlvrwud2y
      - Cloudinary__ApiKey=536731941853732
      - Cloudinary__ApiSecret=Ls8EhXPl8xqhcybYS930AZrpFg0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: altaseb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  postgres_data:
