-- Initial database setup
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" VARCHAR(36) PRIMARY KEY,
    "Username" VARCHAR(100) NOT NULL,
    "Email" VARCHAR(255) NOT NULL UNIQUE,
    "PasswordHash" TEXT NOT NULL,
    "Role" VARCHAR(50) NOT NULL DEFAULT 'User',
    "AvatarUrl" VARCHAR(500),
    "Bio" VARCHAR(300),
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "ChatRooms" (
    "Id" VARCHAR(36) PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    "CreatedByUserId" VARCHAR(36) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_ChatRooms_Users" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "ChatRoomMembers" (
    "UserId" VARCHAR(36) NOT NULL,
    "RoomId" VARCHAR(36) NOT NULL,
    "JoinedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("UserId", "RoomId"),
    CONSTRAINT "FK_ChatRoomMembers_Users" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatRoomMembers_ChatRooms" FOREIGN KEY ("RoomId") REFERENCES "ChatRooms"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Messages" (
    "Id" VARCHAR(36) PRIMARY KEY,
    "Content" VARCHAR(2000) NOT NULL,
    "SenderId" VARCHAR(36) NOT NULL,
    "RoomId" VARCHAR(36) NOT NULL,
    "SentAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsEdited" BOOLEAN NOT NULL DEFAULT FALSE,
    "EditedAt" TIMESTAMP,
    CONSTRAINT "FK_Messages_Users" FOREIGN KEY ("SenderId") REFERENCES "Users"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Messages_ChatRooms" FOREIGN KEY ("RoomId") REFERENCES "ChatRooms"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "PrivateMessages" (
    "Id" VARCHAR(36) PRIMARY KEY,
    "Content" VARCHAR(2000) NOT NULL,
    "SenderId" VARCHAR(36) NOT NULL,
    "RecipientId" VARCHAR(36) NOT NULL,
    "SentAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "FK_PrivateMessages_Sender" FOREIGN KEY ("SenderId") REFERENCES "Users"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PrivateMessages_Recipient" FOREIGN KEY ("RecipientId") REFERENCES "Users"("Id") ON DELETE RESTRICT
);
